export const enum WidgetKind {
  Input = 'input',
  InputGroup = 'input-group',
  Textarea = 'textarea',
  Number = 'number',
  Date = 'date',
  DateRange = 'date-range',
  Time = 'time',
  Toggle = 'toggle',
  Select = 'select',
  Cascader = 'cascader',
  TreeSelect = 'tree-select',
  Slider = 'slider',
  RadioGroup = 'radio-group',
  Checkbox = 'checkbox',
  CheckboxGroup = 'checkbox-group',
  Rate = 'rate',
  Text = 'text',
  Button = 'button',
  ButtonGroup = 'button-group',
  Steps = 'steps',
  Tabs = 'tabs',
  Group = 'group',
  Array = 'array',
}
